<#
.SYNOPSIS
    SailPoint Identity Security Cloud (ISC) - User Access Remediation Execution Engine.
    Executes entitlement removals via Access Requests API and account disablements via Accounts API.

.DESCRIPTION
    Designed for Windows Server node (Execute PowerShell Script) and SailPoint Workflow automation.
    Consumes the 'remediationMap' output generated by Get-RemovalSummary.ps1.

    Actions:
      1. Entitlement Removals: Submits POST /access-requests/v1 (requestType: "REVOKE_ACCESS")
         for each entitlement listed in an account's entitlements array.
      2. Account Disablement: Submits POST /accounts/v1/{id}/disable for accounts flagged
         with needsDisabling = $true.

.PARAMETER RemediationMap
    The remediation map array, JSON string, or file path containing account-to-entitlements data.

.PARAMETER TestMode
    Simulates operations without making live API calls (dry-run mode).

.PARAMETER RateLimitDelaySeconds
    Seconds to wait between API requests to respect SailPoint rate limits (default: 1s).

.PARAMETER Silent
    Suppresses console logs for clean Windows Server node / Workflow JSON stdout.

.OUTPUTS
    Clean JSON object written to stdout containing execution metrics and per-account results.
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory = $true, Position = 0, HelpMessage = "Remediation Map (JSON string, object, array, or file path)")]
    [Alias("Map", "RemediationData", "InputData")]
    $RemediationMap,

    [Parameter(Mandatory = $false, HelpMessage = "Simulate operations without making live changes")]
    [switch]$TestMode,

    [Parameter(Mandatory = $false, HelpMessage = "Delay in seconds between API calls to prevent rate limits")]
    [int]$RateLimitDelaySeconds = 1,

    [Parameter(Mandatory = $false, HelpMessage = "Suppress console logs for clean Windows Server node / Workflow JSON stdout")]
    [switch]$Silent = $false
)

# ==============================================================================
# CONFIGURATION & CREDENTIALS
# ==============================================================================
$Tenant       = "YOUR_TENANT"
$ClientId     = "YOUR_CLIENT_ID"
$ClientSecret = "YOUR_CLIENT_SECRET"

[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
$BaseUrl = "https://$Tenant.api.identitynow.com"

# --- Script Directory & File Logger (logs.txt) ---
$ScriptDirectory = if ($PSScriptRoot) {
    $PSScriptRoot
} elseif ($MyInvocation.MyCommand.Path) {
    Split-Path -Parent $MyInvocation.MyCommand.Path
} else {
    "C:\SailPoint\Scripts\source-access-cleaner"
}
$LogFile = Join-Path -Path $ScriptDirectory -ChildPath "logs.txt"

function Write-Log {
    param(
        [string]$Message,
        [string]$Level = "INFO",
        [string]$ForegroundColor = "White"
    )
    $Timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    $LogLine   = "[$Timestamp] [$Level] $Message"

    # Always log to logs.txt in script directory
    if ($LogFile) {
        try {
            Add-Content -Path $LogFile -Value $LogLine -ErrorAction SilentlyContinue
        } catch {}
    }

    # Console display when not suppressed
    if (-not $Silent) {
        if ($Level -eq "ERROR") {
            Write-Host $LogLine -ForegroundColor Red
        } elseif ($Level -eq "WARN") {
            Write-Host $LogLine -ForegroundColor Yellow
        } else {
            if ($ForegroundColor -and $ForegroundColor -ne "White") {
                Write-Host $LogLine -ForegroundColor $ForegroundColor
            } else {
                Write-Host $LogLine
            }
        }
    }
}

function Log-Host {
    param (
        [string]$Message,
        [string]$ForegroundColor = "White",
        [string]$Level = "INFO"
    )
    if ($ForegroundColor -eq "Red" -or $Message -like "*ERROR*" -or $Message -like "*Failed*") {
        $Level = "ERROR"
    } elseif ($ForegroundColor -eq "Yellow" -or $Message -like "*WARN*" -or $Message -like "*Warning*") {
        $Level = "WARN"
    }
    Write-Log -Message $Message -Level $Level -ForegroundColor $ForegroundColor
}

Write-Log "--- Invoke-AccessRemediation Script Execution Started ---"
if ($TestMode) {
    Write-Log " [TEST MODE ENABLED] Live API requests will be simulated." -Level "WARN"
}

# ------------------------------------------------------------------------------
# 1. Authenticate with SailPoint ISC
# ------------------------------------------------------------------------------
Log-Host "Authenticating to $Tenant ($BaseUrl)..." -ForegroundColor Cyan
$AuthBody = @{
    grant_type    = "client_credentials"
    client_id     = $ClientId
    client_secret = $ClientSecret
}

try {
    $TokenResponse = Invoke-RestMethod -Method Post -Uri "$BaseUrl/oauth/token" -Body $AuthBody
    $AccessToken   = $TokenResponse.access_token
    $Headers       = @{
        "Authorization" = "Bearer $AccessToken"
        "Content-Type"  = "application/json"
        "Accept"        = "application/json"
    }
    Log-Host " Successfully authenticated." -ForegroundColor Green
}
catch {
    $errMsg = "Authentication failed: $($_.Exception.Message)"
    Write-Log -Message $errMsg -Level "ERROR"
    $ErrJson = @{ error = $errMsg; status = "Failed" } | ConvertTo-Json
    Write-Output $ErrJson
    exit 1
}

# ------------------------------------------------------------------------------
# 2. Parse & Validate Remediation Map Input
# ------------------------------------------------------------------------------
$ParsedEntries = [System.Collections.Generic.List[PSCustomObject]]::new()

try {
    $rawObj = $RemediationMap
    if ($RemediationMap -is [string]) {
        $trimmed = $RemediationMap.Trim()
        if (Test-Path $trimmed) {
            Log-Host " Loading remediation map from file: $trimmed..." -ForegroundColor Gray
            $rawObj = Get-Content -Path $trimmed -Raw | ConvertFrom-Json
        } else {
            $rawObj = $trimmed | ConvertFrom-Json
        }
    }

    # Handle wrapped payload from previous workflow step (e.g. { remediationMap: [ ... ] })
    if ($rawObj -is [PSCustomObject] -and $rawObj.PSObject.Properties['remediationMap']) {
        $rawObj = $rawObj.remediationMap
    }

    if ($rawObj -is [System.Collections.IEnumerable] -and -not ($rawObj -is [string])) {
        foreach ($item in $rawObj) {
            $ParsedEntries.Add([PSCustomObject]$item)
        }
    } elseif ($null -ne $rawObj) {
        $ParsedEntries.Add([PSCustomObject]$rawObj)
    }
}
catch {
    $errMsg = "Failed to parse RemediationMap parameter: $($_.Exception.Message)"
    Write-Log -Message $errMsg -Level "ERROR"
    $ErrJson = @{ error = $errMsg; status = "Failed" } | ConvertTo-Json
    Write-Output $ErrJson
    exit 1
}

Log-Host " Loaded $($ParsedEntries.Count) account remediation record(s) for evaluation." -ForegroundColor Cyan

# ------------------------------------------------------------------------------
# 3. Execute Remediations (Entitlement Revocations & Account Disablements)
# ------------------------------------------------------------------------------
$ResultsList = [System.Collections.Generic.List[PSCustomObject]]::new()

$totalEntitlementsRevoked       = 0
$totalEntitlementsFailedToRevoke = 0
$totalAccountsDisabled          = 0
$totalAccountsFailedToDisable   = 0

foreach ($acc in $ParsedEntries) {
    $accId       = $acc.accountId
    $accName     = $acc.accountName
    $idId        = $acc.identityId
    $idUser      = $acc.identityUsername
    $displayName = $acc.identityDisplayName
    $needsDis    = [bool]$acc.needsDisabling
    $isDisabled  = [bool]$acc.isAccountDisabled

    $accResult = [ordered]@{
        accountId              = $accId
        accountName            = $accName
        identityId             = $idId
        identityUsername       = $idUser
        identityDisplayName    = $displayName
        sourceName             = ""
        accountDisabled        = $false
        accountDisableTaskId   = $null
        accountDisableError    = $null
        revokedEntitlements    = [System.Collections.Generic.List[PSCustomObject]]::new()
        failedEntitlements     = [System.Collections.Generic.List[PSCustomObject]]::new()
    }

    # Fetch live account to verify source and state
    $liveAccount = $null
    if ($accId) {
        try {
            $liveAccount = Invoke-RestMethod -Method Get -Uri "$BaseUrl/accounts/v1/$accId" -Headers $Headers
            if ($liveAccount.sourceName) {
                $accResult.sourceName = $liveAccount.sourceName
            }
        } catch {}
    }

    $sourceName = if ($liveAccount -and $liveAccount.sourceName) { $liveAccount.sourceName } else { "Target Source" }

    Log-Host "Processing Remediation for '$accName' ($idUser) on '$sourceName'..." -ForegroundColor Cyan

    # 4A. Entitlement Removals via Access Requests API (POST /access-requests/v1)
    $entCount = if ($null -ne $acc.entitlementCount) { [int]$acc.entitlementCount } else { 0 }
    $entsToRevoke = [System.Collections.Generic.List[PSCustomObject]]::new()
    if ($entCount -gt 0 -and $acc.entitlements) {
        foreach ($entItem in @($acc.entitlements)) {
            if ($entItem -and $entItem.id) {
                $entsToRevoke.Add($entItem)
            }
        }
    }

    # Level 2 Entitlement Verification: If live account authoritatively has no entitlements in ISC, skip revocation
    if ($liveAccount -and $null -ne $liveAccount.hasEntitlements -and -not $liveAccount.hasEntitlements -and $entsToRevoke.Count -gt 0) {
        Log-Host " -> Account '$accName' ($accId) has no active entitlements in ISC (hasEntitlements = false). Skipping revocation." -ForegroundColor Gray
        $entsToRevoke.Clear()
    }

    if ($entsToRevoke.Count -gt 0) {
        Log-Host " -> Found $($entsToRevoke.Count) entitlement(s) to remove for identity $idUser ($idId)." -ForegroundColor Gray

        foreach ($ent in $entsToRevoke) {
            $entId = $ent.id
            $entName = if ($ent.name) { $ent.name } else { $entId }

            if (-not $idId -or -not $entId) {
                Log-Host "    [WARN] Missing identityId or entitlementId for entitlement '$entName'. Skipping." -ForegroundColor Yellow
                $accResult.failedEntitlements.Add([PSCustomObject]@{
                    id    = $entId
                    name  = $entName
                    error = "Missing identityId or entitlementId"
                })
                $totalEntitlementsFailedToRevoke++
                continue
            }

            $revokePayload = [ordered]@{
                requestedFor   = @($idId)
                requestType    = "REVOKE_ACCESS"
                requestedItems = @(
                    [ordered]@{
                        type    = "ENTITLEMENT"
                        id      = $entId
                        comment = "Automated user access remediation - source access cleanup"
                    }
                )
            }
            $revokeJson = $revokePayload | ConvertTo-Json -Depth 5

            if ($TestMode) {
                Write-Log -Message " [TEST MODE] Would submit Access Request revocation for '$entName' ($entId): $revokeJson" -Level "INFO"
                $accResult.revokedEntitlements.Add([PSCustomObject]@{
                    id              = $entId
                    name            = $entName
                    accessRequestId = "SIMULATED_ACCESS_REQUEST"
                    status          = "Simulated"
                })
                $totalEntitlementsRevoked++
            } else {
                try {
                    $reqResponse = Invoke-RestMethod -Method Post -Uri "$BaseUrl/access-requests/v1" -Headers $Headers -Body $revokeJson
                    $reqId = if ($reqResponse.id) { $reqResponse.id } else { "Submitted" }
                    Write-Log -Message " Successfully submitted revocation for entitlement '$entName' ($entId) -> Request ID: $reqId" -Level "INFO"
                    $accResult.revokedEntitlements.Add([PSCustomObject]@{
                        id              = $entId
                        name            = $entName
                        accessRequestId = $reqId
                        status          = "Submitted"
                    })
                    $totalEntitlementsRevoked++
                }
                catch {
                    $errText = $_.Exception.Message
                    Write-Log -Message " Failed to revoke entitlement '$entName' ($entId): $errText" -Level "ERROR"
                    $accResult.failedEntitlements.Add([PSCustomObject]@{
                        id    = $entId
                        name  = $entName
                        error = $errText
                    })
                    $totalEntitlementsFailedToRevoke++
                }

                # Adhere to rate limit
                if ($RateLimitDelaySeconds -gt 0) {
                    Start-Sleep -Seconds $RateLimitDelaySeconds
                }
            }
        }
    } else {
        Log-Host " -> No entitlements flagged for removal for account '$accName'." -ForegroundColor Gray
    }

    # 4B. Account Disablement via POST /accounts/v1/{id}/disable
    if ($needsDis) {
        if ($liveAccount -and $liveAccount.disabled -eq $true) {
            Log-Host " -> Account '$accName' ($accId) is ALREADY disabled in ISC. Skipping disable call." -ForegroundColor Gray
            $accResult.accountDisabled = $true
            $accResult.accountDisableTaskId = "AlreadyDisabled"
        } else {
            Log-Host " -> Disabling account '$accName' (ID: $accId)..." -ForegroundColor Yellow
            $disablePayload = "{}"

            if ($TestMode) {
                Write-Log -Message " [TEST MODE] Would submit POST /accounts/v1/$accId/disable" -Level "INFO"
                $accResult.accountDisabled = $true
                $accResult.accountDisableTaskId = "SIMULATED_DISABLE_TASK"
                $totalAccountsDisabled++
            } else {
                try {
                    $disResponse = Invoke-RestMethod -Method Post -Uri "$BaseUrl/accounts/v1/$accId/disable" -Headers $Headers -Body $disablePayload
                    $taskId = if ($disResponse.id) { $disResponse.id } else { "Submitted" }
                    Write-Log -Message " Successfully submitted disable task for account '$accName' -> Task ID: $taskId" -Level "INFO"
                    $accResult.accountDisabled = $true
                    $accResult.accountDisableTaskId = $taskId
                    $totalAccountsDisabled++
                }
                catch {
                    $errText = $_.Exception.Message
                    Write-Log -Message " Failed to disable account '$accName' ($accId): $errText" -Level "ERROR"
                    $accResult.accountDisableError = $errText
                    $totalAccountsFailedToDisable++
                }

                if ($RateLimitDelaySeconds -gt 0) {
                    Start-Sleep -Seconds $RateLimitDelaySeconds
                }
            }
        }
    } else {
        Log-Host " -> Account '$accName' does not require disablement (needsDisabling = false)." -ForegroundColor Gray
    }

    $ResultsList.Add([PSCustomObject]$accResult)
}

# ------------------------------------------------------------------------------
# 4. Build Final Response & Summary JSON
# ------------------------------------------------------------------------------
$OverallStatus = if ($totalEntitlementsFailedToRevoke -gt 0 -or $totalAccountsFailedToDisable -gt 0) {
    "CompletedWithErrors"
} else {
    "Success"
}

$ExecutionSummary = [ordered]@{
    status                      = $OverallStatus
    testMode                    = [bool]$TestMode
    generatedAt                 = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
    metrics                     = [ordered]@{
        totalAccountsEvaluated      = $ParsedEntries.Count
        accountsDisabled            = $totalAccountsDisabled
        accountsFailedToDisable     = $totalAccountsFailedToDisable
        entitlementsRevoked         = $totalEntitlementsRevoked
        entitlementsFailedToRevoke  = $totalEntitlementsFailedToRevoke
    }
    accountResults              = $ResultsList.ToArray()
}

Write-Log "--- Invoke-AccessRemediation Script Execution Completed (Status: $OverallStatus, Accounts Disabled: $totalAccountsDisabled, Entitlements Revoked: $totalEntitlementsRevoked) ---"

$FinalJson = $ExecutionSummary | ConvertTo-Json -Depth 10
Write-Output $FinalJson

